name: square_recovery

task: &task square
task_config: square_lowdim_abs_obsact
dataset_path: /home/george/diffusion_policy/data/robomimic/datasets/square/ph/low_dim_abs.hdf5

gmm:
  n_components: 6
  save_dir: gmm/${task}/

recovery:
  alpha: 0.00005
  random_walk: 0.008

translator_policy:
  save_dir: translator/${task}/
  checkpoint_used: /home/george/diffusion_policy/data/outputs/2024.09.11/08.56.33_train_diffusion_unet_lowdim_obsact_square_lowdim/checkpoints/epoch=0400-train_action_mse_error=0.003.ckpt

base_policy:
  checkpoint_used: /home/george/diffusion_policy/data/outputs/2024.09.05/16.12.10_train_diffusion_unet_lowdim_square_lowdim_abs/checkpoints/epoch=0250-test_mean_score=0.960.ckpt
